import { MongoClient, ObjectId } from "mongodb";
import { readFile } from "node:fs/promises";
import path from "node:path";

const MONGO_URI = "mongodb://localhost:7777";

// Set to false for dry-run, true for real database updates
const IS_REAL_RUN = false;

// Configuration for HackGT 13 top 50% accepted without travel
const INPUT_JSON_FILE = path.resolve(__dirname, "../output/hackgt13_top50_candidates.json");
const NEW_STATUS = "ACCEPTED";
const CONFIRMATION_BRANCH_ID = "6a8e630570e73013f82814ba"; // accepted without travel

let APPLICATION_IDS: string[] = [];

async function run() {
  console.log(`📂 Loading application IDs from: ${INPUT_JSON_FILE}`);

  // Read the JSON file generated by selectTop50PercentWithReferrals.ts
  const jsonData = await readFile(INPUT_JSON_FILE, "utf-8");
  const parsed = JSON.parse(jsonData);
  APPLICATION_IDS = parsed.selectedApplicationIds;

  console.log(`\n✅ Loaded ${APPLICATION_IDS.length} application IDs.`);
  console.log(`📊 Metadata from input file:`);
  console.log(`   - Total applications in branch: ${parsed.totalApplications}`);
  console.log(`   - Top 50% count: ${parsed.top50PercentCount}`);
  console.log(`   - Excluded (already in travel reimbursement): ${parsed.alreadyInTravelReimbursement}`);
  console.log(`   - Final eligible count: ${parsed.eligibleCount}`);

  if (APPLICATION_IDS.length === 0) {
    throw new Error("APPLICATION_IDS must contain at least one application ID.");
  }
  if (APPLICATION_IDS.some(id => !ObjectId.isValid(id))) {
    throw new Error("APPLICATION_IDS must contain only valid application IDs.");
  }
  if (CONFIRMATION_BRANCH_ID !== undefined && !ObjectId.isValid(CONFIRMATION_BRANCH_ID)) {
    throw new Error("CONFIRMATION_BRANCH_ID must be a valid branch ID.");
  }

  const client = new MongoClient(MONGO_URI);

  try {
    await client.connect();
    console.log("\n✅ Successfully connected to MongoDB.");

    const applications = client.db("registration").collection("applications");
    const update: any = {
      $set: {
        status: NEW_STATUS,
      },
    };

    if (CONFIRMATION_BRANCH_ID !== undefined) {
      update.$set.confirmationBranch = new ObjectId(CONFIRMATION_BRANCH_ID);
    }

    const updateQuery = {
      _id: { $in: APPLICATION_IDS.map(id => new ObjectId(id)) },
    };

    if (IS_REAL_RUN) {
      console.log("\n⚡ Performing REAL RUN: Updating applications...");
      const result = await applications.updateMany(updateQuery, update);
      console.log(`\n✅ Success! ${result.modifiedCount} application(s) updated.`);
      console.log(`   - Status updated to: ${NEW_STATUS}`);
      console.log(`   - Confirmation branch set to: ${CONFIRMATION_BRANCH_ID}`);
    } else {
      console.log("\n🔎 DRY RUN: Previewing changes (no database updates)...");
      const matchCount = await applications.countDocuments(updateQuery);
      console.log(`\n📋 Would update ${matchCount} application(s):`);
      console.log(`   - Status would be updated to: ${NEW_STATUS}`);
      console.log(`   - Confirmation branch would be set to: ${CONFIRMATION_BRANCH_ID}`);
      console.log(`\n⚠️  To perform the actual update, change IS_REAL_RUN to true at the top of this file.`);
    }
  } finally {
    await client.close();
  }
}

(async () => {
  try {
    await run();
    console.info("\n✅ Done.");
  } catch (error) {
    console.error("\n❌ Failed:", error);
    process.exitCode = 1;
  }
})();
