export const prizeConfig = {
  hexathons: {
    "HackGT 7": {
      emergingPrizes: [
        "Emerging: Best Overall",
        "Emerging: Most Impactful",
        "Emerging: Most Creative",
        "Emerging: Best Design",
        "Best Web Dev Track",
        "Best Data Science Track",
        "Best Video Game Dev Track",
        "Best Mobile App Dev Track",
      ],
      sponsorPrizes: [
        "NCR - Disruptive and innovative solution",
        "BlackRock - Best chatbot",
        "Anthem - Digital medicine",
        "Capital One - Best financial hack",
        "Facebook - Spark AR",
        "IBM - Community response to COVID-19",
        "Microsoft Azure - Champ prize (Hack for Good)",
        "NewsQ - Social good",
        "NSIN - Visualize tool",
        "NSIN - Fitness tracker interface",
        "MLH - Best domain",
        "MLH - Best use of Google Cloud",
        "MLH - Best hardware hack",
        "MLH - Best use of DataStax Astra",
      ],
    },
    "HackGT 8": {
      generalPrizes: [
        "HackGT - Best Social Impact",
        "HackGT - Best Design",
        "HackGT - Best Hardware Hack",
        "HackGT - Most Sustainable Hack",
        "HackGT - Most Unique/Out of the Box/Creative",
      ],
      openSourcePrizes: ["HackGT - Best Open Source Hack"],
      emergingPrizes: [
        "Emerging - Best Overall",
        "Emerging - Best in App/Web Development",
        "Emerging - Best in Data Science",
        "Emerging - Best in Design",
        "Emerging - Best in Systems",
        "Emerging - Best Prototype",
        "Emerging - Best Presentation",
      ],
      sponsorPrizes: [
        "NCR - Best Use of NCR APIs",
        "NCR - Best Use of Cryptocurrency",
        "NCR - Retail Gamification",
        "NCR - Machine Learning in Retail",
        "BlackRock - Best Overall",
        "Anthem - Best Overall",
        "NSA - Secure the Server",
        "NSA - Secure Code Zero Trust",
        "Best Use of Google Cloud",
      ],
    },
    "Horizons 2022": {
      tracks: ["Digital Track", "Physical Track"],
      challenges: ["Sustainability Challenge", "Educational Challenge", "Music Tech Challenge"],
    },
    "Horizons 2023": {
      tracks: ["Digital Track", "Physical Track"],
      challenges: [
        "Accessibility Challenge",
        "Educational Challenge",
        "Music Tech Challenge",
        "Mixed Reality Challenge",
      ],
    },
    "Prototypical 2022": {
      tracks: ["Textiles Track", "Cardboard Track"],
    },
    "HackGT 9": {
      generalPrizes: [
        "HackGT - Effortlessly Entertaining",
        "HackGT - Retro Hack",
        "HackGT - Altruistic Hack",
        "HackGT - Twisted Reality",
        "HackGT - Upgrade!",
        "HackGT - Data-Driven",
        "HackGT - Cheat Code Hack",
      ],
      emergingPrizes: [
        "Emerging - Best Hardware Hack",
        "Emerging - Best Application",
        "Emerging - Best Expo Pitch",
        "Emerging - Best Design",
      ],
      sponsorPrizes: [
        "BlackRock - Best Overall",
        "T-Mobile - Privacy & Information Security",
        "Carelon - Best Overall",
      ],
    },
    "HackGT X": {
      generalPrizes: [
        "General - Digital Art 4510",
        "General - Innovate 3251",
        "General - Sustain 2110",
        "General - Edu 3510",
        "General - Health 1001",
      ],
      emergingPrizes: [
        "Emerging - Digital Art 4510",
        "Emerging - Innovate 3251",
        "Emerging - Sustain 2110",
        "Emerging - Edu 3510",
        "Emerging - Health 1001",
      ],
      sponsorPrizes: [
        "Capital One - Best Financial Hack",
        "Drive Capital Challenge",
        "MLH - Most Creative Use of Github",
        "MLH - Best Use of MongoDB Atlas",
        "MLH - Best Use of Soroban",
        "MLH - Best Use of MATLAB",
        "MLH - Best .Tech Domain Name",
        "MLH - Best Use of Google Cloud",
        "MLH - Best Accessibility Hack",
      ],
    },
    "Horizons 2024": {
      tracks: ["Digital Track", "Physical Track"],
      challenges: ["Education Challenge", "Music Tech Challenge", "Mixed Reality Challenge"],
    },
    "HackGT 11": {
      generalPrizes: [
        "General - Scooter",
        "General - Nintendo Switch",
        "General - Kindle",
        "Analytics Arcade - Fitbit",
        "AI Funhouse - Beats",
        "Magical Midway - JBL Speaker",
        "Carnival for a Cause - Photo Printer",
      ],
      emergingPrizes: ["Emerging - Monitor", "Emerging - Lego Set", "Emerging - Blender"],
      sponsorPrizes: ["Sponsor - Electric Skateboard"],
    },
  },
};
